name: MSBuild
on: push
jobs:
  build:
    name: MSBuild
    runs-on: self-hosted
    steps:
    - name: Check cmd
      shell: cmd
      run: |
        echo "############"
        echo "cmd OK!"
        echo "############"
        chdir
    
    - name: Check pwsh
      shell: pwsh
      run: |
        echo "############"
        echo "pwsh OK!"
        echo "############"
        # chdir

    - name: Check bash
      shell: bash
      run: |
        echo "############"
        echo "bash OK!"
        echo "############"
        chdir
