name: MSBuild
on: 
  push:
   branches:
    - main
jobs:
  build:
    name: build-job
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        clean: false

    - name: build
      shell: cmd
      run: |
        set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
        set PATH=C:\3rdparty\opencv\build\x64\vc15\bin;%PATH%
        echo "build on windows"
        :# MSBuild sample\sample1\sample1.vcxproj /t:rebuild /p:Configuration=Release;Platform=x64
        :# MSBuild sample\test_sample1\test_sample1.vcxproj /t:rebuild /p:Configuration=Release;Platform=x64
        MSBuild sample\sample2\sample2.vcxproj /t:rebuild /p:Configuration=Release;Platform=x64
        MSBuild sample\test_sample2\test_sample2.vcxproj /t:rebuild /p:Configuration=Release;Platform=x64
        echo "build successful!"

  test:
    name: test-job
    runs-on: self-hosted
    steps:
    - name: test
      shell: cmd
      run: |
        :# set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
        :# set PATH=C:\3rdparty\opencv\build\x64\vc15\bin;%PATH%
        echo "test on windows"
        :# sample\test_sample1\x64\Release\test_sample1.exe
        sample\test_sample2\x64\Release\test_sample2.exe
        echo "test successful!!"
