name: Test CI/CD
on: 
  push:
   branches:
    - main
jobs:
  build:
    name: build-job
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Checkout
      uses: actions/checkout@main
      with:
        clean: false

    - name: test shell
      shell: cmd
      run: |
        echo "hello world"
        dir
        chdir
        