name: Test CI/CD
on: 
  push:
   branches:
    - main
jobs:
  build:
    name: build-job
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: build
      shell: cmd
      run: |
        set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
        rmdir /s /q sample-app\x64\Release
        MSBuild sample-app\sample-app.sln /t:rebuild /p:Configuration=Release;Platform=x64
        xcopy sample-app\sample-app\config.ini sample-app\x64\Release
    - name: copy-build-artifacts
      shell: cmd
      run: |
        rmdir /s /q path\to\artifacts
        mkdir path\to\artifacts
        xcopy sample-app\x64\Release path\to\artifacts
    - uses: actions/upload-artifact@v3
      with: 
        name: build-artifacts
        path: path/to/artifacts

  test:
    name: test-job
    needs: build
    runs-on: windows-2019
    steps:
    - uses: actions/download-artifact@v3
      name: download-build-artifact
      with:
        name: build-artifacts
        path: artifacts
    - name: test shell
      shell: cmd
      run: |
        echo "hello world"
        cd artifacts
        sample-app.exe
