name: Test CI/CD
on: 
  push:
   branches:
    - main
jobs:
  build:
    name: build-job
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        clean: false

    - name: build
      shell: cmd
      run: |
        chcp 65001
        set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
        rmdir /s /q sample-app\x64\Release
        MSBuild sample-app\sample-app.sln /t:rebuild /p:Configuration=Release;Platform=x64
        xcopy sample-app\sample-app\config.ini sample-app\x64\Release

  test:
    name: test-job
    needs: build
    runs-on: self-hosted
    steps:
    - name: test
      shell: cmd
      run: |
        chcp
        chcp 932
        chcp
        set PATH=C:\3rdparty\opencv\build\x64\vc15\bin;%PATH%
        sample-app\x64\Release\unittest.exe

    - name: copy
      shell: cmd
      run: |
        chcp 65001
        rmdir /s /q path\to\artifact
        mkdir path\to\artifact
        xcopy sample-app\x64\Release path\to\artifact
    - uses: actions/upload-artifact@v3
      with: 
        name: my-artifact
        path: path/to/artifact

  deploy:
    name: deploy-job
    needs: test
    runs-on: self-hosted
    steps:
    - uses: actions/download-artifact@v3
      name: deploy
      with:
        name: my-artifact
        path: C:\Users\NES\Desktop\deploy
